
image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public

tasks:
  - init: npm install
    command: npm run dev
    
vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - alefragnani.bookmarks
    - coenraads.bracket-pair-colorizer-2
    - zignd.html-css-class-completion
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
    - ecmel.vscode-html-css
    - vscode-icons-team.vscode-icons
